import tkinter as tk
from tkinter import ttk
from tkinter.scrolledtext import ScrolledText


class CommandLine(ttk.Notebook):
    """
    The Pyssembler Command Line and MIPS32 Output as tabs
    """
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)
        self.__init_ui()
    
    def __init_ui(self):
        self.cmd = PyssemblerCMD(self)
        self.add(self.cmd, text='CMD')
        self.mips_out = MIPS32Output(self)
        self.add(self.mips_out, text='MIPS OUTPUT')

class PyssemblerCMD(ScrolledText):
    """
    The Pyssembler Command Line 
    """
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)
        self.insert(tk.INSERT, 'CMD')

class MIPS32Output(ScrolledText):
    """
    Displays the output generated by simulating a MIPS32 program
    """
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)
        self.insert(tk.INSERT, 'MIPS OUTPUT FROM SIMULATION')